"""empty message

Revision ID: 135eb7213f36
Revises: 465cc491db81
Create Date: 2023-01-25 22:14:29.375837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135eb7213f36'
down_revision = '465cc491db81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ws_store', sa.Column('hours_ws_store', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ws_store', 'hours_ws_store')
    # ### end Alembic commands ###
