"""empty message

Revision ID: 2e0d16f94eaf
Revises: 
Create Date: 2023-01-25 11:10:45.938091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0d16f94eaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=250), nullable=False),
    sa.Column('last_name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ws_store',
    sa.Column('id_ws', sa.Integer(), nullable=False),
    sa.Column('name_ws_store', sa.String(length=250), nullable=False),
    sa.Column('email_ws_store', sa.String(length=250), nullable=False),
    sa.Column('password_ws_store', sa.String(length=250), nullable=False),
    sa.Column('address_ws_store', sa.String(length=250), nullable=False),
    sa.Column('scheduling_ws_store', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_ws')
    )
    op.create_table('inventory',
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=False),
    sa.Column('product', sa.String(length=250), nullable=False),
    sa.Column('picture', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('ws_store')
    op.drop_table('user')
    # ### end Alembic commands ###
