"""empty message

Revision ID: a4f5cef60369
Revises: 
Create Date: 2023-01-21 16:41:03.363093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f5cef60369'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('status_commit', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_table('scheduling',
    sa.Column('id_scheduling', sa.Integer(), nullable=False),
    sa.Column('start_hour', sa.String(length=250), nullable=False),
    sa.Column('end_hour', sa.String(length=250), nullable=False),
    sa.Column('day', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_scheduling')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('last_name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('type', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=False),
    sa.Column('product', sa.String(length=250), nullable=False),
    sa.Column('picture', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('user')
    op.drop_table('scheduling')
    op.drop_table('order')
    # ### end Alembic commands ###
