export const products = [
  {
    category: "Repuestos",
    subcategory: "Freno",
    name: "TIAGRA SHIMANO",
    price: "10.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812731/categoria/frenos1_gbimuz.png",
    id: 1,
    user_id: 6,
  },
  {
    category: "Repuestos",
    subcategory: "Freno",
    name: "AVID SINGLE 7 DIGIT",
    price: "12.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812731/categoria/frenos_2_c7ia8t.png",
    id: 2,
    user_id: 6,
  },
  {
    category: "Repuestos",
    subcategory: "cadena",
    name: "VIA",
    price: "15.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812721/categoria/cadena_2_ykh6sb.jpg",
    id: 3,
    user_id: 6,
  },
  {
    category: "Repuestos",
    subcategory: "cadena",
    name: "LG50 SHIMANO",
    price: "15.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812716/categoria/cadena_1_bjts3y.jpg",
    id: 4,
    user_id: 6,
  },
  {
    category: "Bicicletas",
    subcategory: "Bicicleta de montaña",
    name: "PIVOT",
    price: "600.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812756/categoria/monta%C3%B1era_1_x4oilm.png",
    id: 5,
    user_id: 6,
  },
  {
    category: "Bicicletas",
    subcategory: "Bicicleta de montaña",
    name: "ORANGE ALPINA",
    price: "600.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812755/categoria/monta%C3%B1era_2_xkeqt1.png",
    id: 6,
    user_id: 6,
  },
  {
    category: "Bicicletas",
    subcategory: "Bicicleta de ruta",
    name: "FOCUS",
    price: "600.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812747/categoria/ruta_1_uqpso9.png",
    id: 7,
    user_id: 6,
  },
  {
    category: "Bicicletas",
    subcategory: "Bicicleta de ruta",
    name: "LIVALL",
    price: "600.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812747/categoria/ruta_2_fijau7.png",
    id: 8,
    user_id: 6,
  },
  {
    category: "Accesorios",
    subcategory: "Cascos",
    name: "BELL",
    price: "80.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812770/categoria/casco_1_b29rmn.png",
    id: 9,
    user_id: 6,
  },
  {
    category: "Accesorios",
    subcategory: "Cascos",
    name: "CUBE",
    price: "70.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812770/categoria/casco_2_twgv8d.png",
    id: 10,
    user_id: 6,
  },
  {
    category: "Accesorios",
    subcategory: "Bombin",
    name: "RENKOMPRESSOR",
    price: "100.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812764/categoria/bomba_1_qk9pfe.png",
    id: 11,
    user_id: 6,
  },
  {
    category: "Accesorios",
    subcategory: "Bombin",
    name: "KAMASA",
    price: "120.000",
    img: "https://res.cloudinary.com/duyceuv9y/image/upload/v1675812764/categoria/bomba_2_lbtqal.png",
    id: 12,
    user_id: 6,
  },
];
